import type { CompanySettings } from './types'
import { lsGet } from './persist'

export const defaultCompanySettings: CompanySettings = {
  companyName: 'Amazonia Concrete',
  slogan: 'Belleza natural en concreto',
  email: '',
  phone: '',
  address: '',
  currency: 'COP',
  timezone: 'America/Bogota',
  logo: lsGet<string | null>('erp_logo', null),
  bankName: 'Bancolombia',
  bankKey: '',
  bankAccountType: 'Cuenta Ahorros',
  bankAccountNumber: '',
  bankMessage: '',
  tiktok: '',
  whatsapp: '',
  instagram: '',
  instagramHandle: '',
  smtpHost: '',
  smtpPort: 587,
  smtpUser: '',
  smtpPass: '',
  smtpFrom: '',
  invoicePrefix: 'VTA',
  monthlyGoal: 0,
  taxRate: 0.19,
  paymentMethods: [
    { id: 'cash',      name: 'Efectivo',      isActive: true },
    { id: 'transfer',  name: 'Transferencia', isActive: true },
    { id: 'nequi',     name: 'Nequi',         isActive: true },
    { id: 'daviplata', name: 'Daviplata',     isActive: true },
    { id: 'card',      name: 'Tarjeta',       isActive: true },
    { id: 'check',     name: 'Cheque',        isActive: false },
  ],
  taxRates: [
    { id: 'iva19',  name: 'IVA 19%', rate: 0.19, isDefault: true,  isActive: true },
    { id: 'iva0',   name: 'IVA 0%',  rate: 0,    isDefault: false, isActive: true },
    { id: 'exento', name: 'Exento',  rate: 0,    isDefault: false, isActive: true },
  ],
  teamMembers: [
    { id: 'tm_s1', name: 'Ana Ramos',      role: 'seller',     isActive: true },
    { id: 'tm_s2', name: 'Carlos López',   role: 'seller',     isActive: true },
    { id: 'tm_s3', name: 'María García',   role: 'seller',     isActive: true },
    { id: 'tm_s4', name: 'Roberto Méndez', role: 'seller',     isActive: true },
    { id: 'tm_s5', name: 'Admin General',  role: 'seller',     isActive: true },
    { id: 'tm_p1', name: 'Carlos Mendez',  role: 'production', isActive: true },
    { id: 'tm_p2', name: 'Laura Herrera',  role: 'production', isActive: true },
    { id: 'tm_p3', name: 'Miguel Torres',  role: 'production', isActive: true },
    { id: 'tm_d1', name: 'Carlos López',   role: 'driver',     isActive: true },
    { id: 'tm_d2', name: 'Miguel Herrera', role: 'driver',     isActive: true },
    { id: 'tm_d3', name: 'Andrés Ruiz',    role: 'driver',     isActive: true },
    { id: 'tm_d4', name: 'Pedro Díaz',     role: 'driver',     isActive: true },
    { id: 'tm_d5', name: 'Juan Martínez',  role: 'driver',     isActive: true },
  ],
}
